name: Build artifact with maven

on:
  workflow_call:
    inputs:
      display-name:
        description: 'Display name'
        required: true
        type: string

      jdk:
        description: 'JDK to use'
        default: '17'
        required: false
        type: string
      jdk-distribution:
        description: 'JDK distribution to use'
        default: 'temurin'
        required: false
        type: string
      publish:
        description: 'Enable publish step?'
        default: false
        required: false
        type: boolean
      sonar:
        description: 'Enable sonar step?'
        default: false
        required: false
        type: boolean
      sonar-project-key:
        description: 'Sonar project key'
        default: ''
        required: false
        type: string
    secrets:
      sonar-token:
        description: 'Sonar token'
        required: false

jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ inputs.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.jdk-distribution }}
          cache: maven

      - name: Compile ${{ inputs.display-name }}
        run: mvn --batch-mode compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test ${{ inputs.display-name }}
        run: mvn --batch-mode test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sonar
        if: ${{ inputs.sonar }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.sonar-project-key }} -DskipTests

      - name: Publish ${{ inputs.display-name }}
        if: ${{ inputs.publish }}
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
