name: Build artifact with maven

on:
  workflow_call:
    inputs:
      display-name:
        description: 'Display name'
        required: true
        type: string

      jdk:
        description: 'JDK to use'
        default: '17'
        required: false
        type: string
      jdk-distribution:
        description: 'JDK distribution to use'
        default: 'temurin'
        required: false
        type: string
      publish:
        description: 'Is artifact should be published?'
        default: false
        required: false
        type: boolean

jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ inputs.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.jdk-distribution }}
          cache: maven

      - name: Build ${{ inputs.display-name }}
        run: mvn --batch-mode clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ${{ inputs.display-name }}
        if: ${{ inputs.publish }}
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
